name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Bazel Artifacts
      uses: actions/cache@v3
      env:
        cache-name: bazel-cache
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Java
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '17.0.8'
    - name: "Build"
      run: |
        bazel build //...
    - name: "Test"
      run: |
        bazel test //...
