name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '17'
    - name: "Build"
      run: |
        bazel build //...
    - name: "Test"
      run: |
        bazel test //...
